package de.mediguard.config;

import de.mediguard.auth.JwtAuthFilter;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.AuthenticationProvider;
import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.annotation.web.configurers.HeadersConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.CorsConfigurationSource;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;

import java.util.Arrays;
import java.util.List;

/**
 * FIXED:
  * 1. @Lazy dihapus — UserDetailsServiceImpl memutus circular dependency
   * 2. userDetailsService() bean dihapus — ada di UserDetailsServiceImpl.java
    * 3. @RequiredArgsConstructor untuk constructor injection yang bersih
     * 4. Security headers diperketat (DENY, HSTS)
      */
      @Configuration
      @EnableWebSecurity
      @EnableMethodSecurity
      @RequiredArgsConstructor
      public class SecurityConfig {

          private final JwtAuthFilter jwtAuthFilter;
              private final UserDetailsService userDetailsService; // → UserDetailsServiceImpl

                  @Value("${mediguard.cors.allowed-origins}")
                      private String allowedOrigins;

                          @Bean
                              public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
                                      return http
                                                      .csrf(AbstractHttpConfigurer::disable)
                                                                      .cors(cors -> cors.configurationSource(corsConfigurationSource()))
                                                                                      .sessionManagement(s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                                                                                                      .authorizeHttpRequests(auth -> auth
                                                                                                                              .requestMatchers(
                                                                                                                                                              "/api/v1/auth/**",
                                                                                                                                                                                              "/swagger-ui/**",
                                                                                                                                                                                                                              "/swagger-ui.html",
                                                                                                                                                                                                                                                              "/api-docs/**",
                                                                                                                                                                                                                                                                                              "/h2-console/**",
                                                                                                                                                                                                                                                                                                                              "/actuator/health"
                                                                                                                                                                                                                                                                                                                                                      ).permitAll()
                                                                                                                                                                                                                                                                                                                                                                              .anyRequest().authenticated()
                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                              .headers(h -> h
                                                                                                                                                                                                                                                                                                                                                                                                                                      .frameOptions(HeadersConfigurer.FrameOptionsConfig::deny)
                                                                                                                                                                                                                                                                                                                                                                                                                                                              .contentTypeOptions(c -> {})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .httpStrictTransportSecurity(hsts -> hsts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .includeSubDomains(true)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .maxAgeInSeconds(31536000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .authenticationProvider(authenticationProvider())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .addFilterBefore(jwtAuthFilter, UsernamePasswordAuthenticationFilter.class)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .build();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      @Bean
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          public AuthenticationProvider authenticationProvider() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var provider = new DaoAuthenticationProvider();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          provider.setUserDetailsService(userDetailsService);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  provider.setPasswordEncoder(passwordEncoder());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return provider;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  @Bean
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      public AuthenticationManager authenticationManager(AuthenticationConfiguration config)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  throws Exception {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return config.getAuthenticationManager();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  @Bean
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      public PasswordEncoder passwordEncoder() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new BCryptPasswordEncoder(12);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      @Bean
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          public CorsConfigurationSource corsConfigurationSource() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var config = new CorsConfiguration();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          config.setAllowedOrigins(Arrays.asList(allowedOrigins.split(",")));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  config.setAllowedMethods(List.of("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          config.setAllowedHeaders(List.of("Authorization", "Content-Type", "Accept"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  config.setAllowCredentials(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          config.setMaxAge(3600L);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var source = new UrlBasedCorsConfigurationSource();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          source.registerCorsConfiguration("/**", config);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return source;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      